import { Router } from 'express'; import crypto from 'node:crypto';
import bcrypt from 'bcryptjs';
import jwt from 'jsonwebtoken';
import { z } from 'zod';
import { prisma } from '../prisma.js';
import { config } from '../config.js';
import { AppError } from '../lib/errors.js';
import { requireAuth } from '../middleware/auth.js';
import { validate } from '../middleware/validate.js';
import { audit } from '../lib/audit.js';
const router = Router();
const publicUser = (u: any) => ({ id:u.id, firstName:u.firstName, lastName:u.lastName, email:u.email, profileImageUrl:u.profileImageUrl, isActive:u.isActive, role:u.role.name, lastLoginAt:u.lastLoginAt });
const setCookie = (res: any, user: any) => res.cookie('session', jwt.sign({ id:user.id, role:user.role.name, email:user.email }, config.jwtSecret, { expiresIn: config.jwtExpiresIn }), { httpOnly:true, secure:config.isProduction, sameSite:config.isProduction ? 'none' : 'lax', maxAge: 7*24*60*60*1000 });
router.post('/login', validate(z.object({ email:z.string().email(), password:z.string().min(1) })), async (req,res,next) => { try { const user=await prisma.user.findUnique({where:{email:req.body.email},include:{role:true}}); if(!user||!user.isActive||!(await bcrypt.compare(req.body.password,user.passwordHash))) throw new AppError(401,'Invalid email or password.'); await prisma.user.update({where:{id:user.id},data:{lastLoginAt:new Date()}}); setCookie(res,user); res.json({user:publicUser(user)}); } catch(e){next(e)} });
router.post('/logout', (_req,res) => { res.clearCookie('session'); res.status(204).end(); });
router.get('/me', requireAuth, async (req,res,next) => { try { const user=await prisma.user.findUnique({where:{id:req.user!.id},include:{role:true}}); if(!user||!user.isActive) throw new AppError(401,'Session is no longer valid.'); res.json({user:publicUser(user)}); }catch(e){next(e)} });
router.post('/change-password', requireAuth, validate(z.object({ currentPassword:z.string(), newPassword:z.string().min(8,'Password must be at least 8 characters.') })), async(req,res,next)=>{try{const user=await prisma.user.findUnique({where:{id:req.user!.id}});if(!user||!(await bcrypt.compare(req.body.currentPassword,user.passwordHash)))throw new AppError(400,'Current password is incorrect.');await prisma.user.update({where:{id:user.id},data:{passwordHash:await bcrypt.hash(req.body.newPassword,12)}});await audit(user.id,'PASSWORD_CHANGED','User',user.id);res.status(204).end()}catch(e){next(e)}});
router.post('/forgot-password', validate(z.object({email:z.string().email()})), async(req,res,next)=>{try{const user=await prisma.user.findFirst({where:{email:req.body.email,isActive:true}});let developmentToken: string|undefined;if(user){const token=crypto.randomBytes(32).toString('hex');developmentToken=token;await prisma.user.update({where:{id:user.id},data:{passwordResetTokenHash:crypto.createHash('sha256').update(token).digest('hex'),passwordResetExpiresAt:new Date(Date.now()+30*60*1000)}})}res.json({message:'If an active account exists, a reset instruction has been sent.',...(!config.isProduction&&developmentToken?{developmentToken}:{})})}catch(e){next(e)}});
router.post('/reset-password', validate(z.object({token:z.string().min(1),newPassword:z.string().min(8)})), async(req,res,next)=>{try{const hash=crypto.createHash('sha256').update(req.body.token).digest('hex');const user=await prisma.user.findFirst({where:{passwordResetTokenHash:hash,passwordResetExpiresAt:{gt:new Date()},isActive:true}});if(!user)throw new AppError(400,'This reset link is invalid or has expired.');await prisma.user.update({where:{id:user.id},data:{passwordHash:await bcrypt.hash(req.body.newPassword,12),passwordResetTokenHash:null,passwordResetExpiresAt:null}});await audit(user.id,'PASSWORD_CHANGED','User',user.id);res.status(204).end()}catch(e){next(e)}});
export default router;
