import { Router } from 'express';
import { RoleName } from '@prisma/client'; import { z } from 'zod';
import { prisma } from '../prisma.js'; import { requireAuth } from '../middleware/auth.js'; import { validate } from '../middleware/validate.js'; import { AppError } from '../lib/errors.js'; import { audit } from '../lib/audit.js'; import { expenseWhere,pageArgs } from '../lib/query.js';
const router=Router(); const schema=z.object({userId:z.string().optional(),responsibilityId:z.string().min(1),subItemId:z.string().nullable().optional(),expenseDate:z.coerce.date(),amount:z.coerce.number().positive(),remark:z.string().max(1000).nullable().optional()});
const include={user:{select:{id:true,firstName:true,lastName:true,email:true}},responsibility:true,subItem:true};
const routeParam=(value:string|string[]|undefined)=>Array.isArray(value)?value[0]||'':value||'';
async function assertAllowed(actor:any,responsibilityId:string){if(actor.role===RoleName.ADMIN)return;const assigned=await prisma.userResponsibility.findUnique({where:{userId_responsibilityId:{userId:actor.id,responsibilityId}}});const responsibility=await prisma.responsibility.findUnique({where:{id:responsibilityId}});if(!assigned||!responsibility?.isActive)throw new AppError(403,'This responsibility is not assigned to you.');}
router.get('/',requireAuth,async(req,res,next)=>{try{const where=expenseWhere(req.user!,req.query as any);const page=pageArgs(req.query);const [data,total]=await Promise.all([prisma.expense.findMany({where,...page,include,orderBy:[{expenseDate:'desc'},{createdAt:'desc'}]}),prisma.expense.count({where})]);res.json({data,total,page:Number(req.query.page)||1,limit:page.take})}catch(e){next(e)}});
router.post('/',requireAuth,validate(schema),async(req,res,next)=>{try{const targetUserId=req.user!.role===RoleName.ADMIN&&req.body.userId?req.body.userId:req.user!.id;await assertAllowed(req.user!,req.body.responsibilityId);if(req.body.subItemId){const sub=await prisma.responsibilitySubItem.findFirst({where:{id:req.body.subItemId,responsibilityId:req.body.responsibilityId,isActive:true}});if(!sub)throw new AppError(400,'Sub-item does not belong to this responsibility.');}const expense=await prisma.expense.create({data:{...req.body,userId:targetUserId,createdById:req.user!.id},include});await audit(req.user!.id,'EXPENSE_CREATED','Expense',expense.id);res.status(201).json(expense)}catch(e){next(e)}});
router.patch('/:id',requireAuth,validate(schema.partial()),async(req,res,next)=>{try{const old=await prisma.expense.findUnique({where:{id:routeParam(req.params.id)}});if(!old)throw new AppError(404,'Expense not found.');if(req.user!.role===RoleName.MEMBER&&old.userId!==req.user!.id)throw new AppError(403,'Access denied.');const responsibilityId=req.body.responsibilityId||old.responsibilityId;if(req.body.responsibilityId)await assertAllowed(req.user!,responsibilityId);if(req.body.subItemId){const sub=await prisma.responsibilitySubItem.findFirst({where:{id:req.body.subItemId,responsibilityId,isActive:true}});if(!sub)throw new AppError(400,'Sub-item does not belong to this responsibility.');}const data:any={...req.body,updatedById:req.user!.id};delete data.userId;const expense=await prisma.expense.update({where:{id:old.id},data,include});await audit(req.user!.id,'EXPENSE_UPDATED','Expense',expense.id);res.json(expense)}catch(e){next(e)}});
router.delete('/:id',requireAuth,async(req,res,next)=>{try{const expense=await prisma.expense.findUnique({where:{id:routeParam(req.params.id)}});if(!expense)throw new AppError(404,'Expense not found.');if(req.user!.role===RoleName.MEMBER&&expense.userId!==req.user!.id)throw new AppError(403,'Access denied.');await prisma.expense.delete({where:{id:expense.id}});await audit(req.user!.id,'EXPENSE_DELETED','Expense',expense.id);res.status(204).end()}catch(e){next(e)}});
export default router;
